# Generated by Django 6.0 on 2025-12-20 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rifuser',
            name='is_admin',
        ),
    ]
