# Generated by Django 6.0 on 2025-12-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_rifuser_is_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifuser',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
