# Generated by Django 6.0 on 2026-01-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rifuser_is_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifuser',
            name='username',
            field=models.CharField(default=None, max_length=150, unique=True),
        ),
    ]
