# Generated by Django 6.0 on 2026-01-06 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_rifuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
