# Generated by Django 6.0 on 2026-01-06 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rifuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
