# Generated by Django 6.0 on 2026-01-06 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_rifuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifuser',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
